name: PKUAutoSubmit

on:
  schedule:
    - cron: '0 1 * * 5'
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
           python-version: 3.7
           
      - name: 'Install requirements'
        run: 
          pip install selenium
        
      - name: 'Working'
        run:
          python main.py --userName ${{secrets.userName}} --passWord ${{secrets.passWord}} --space ${{secrets.space}} --day ${{secrets.day}} --time ${{secrets.time}} --booktime ${{secrets.booktime}}
          

