name: PKUCourtAuto

on:
  schedule:
    - cron: '00 12 22 3 *'
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
           python-version: 3.7
           
      - name: 'Install requirements'
        run: 
          pip install selenium
        
      - name: 'Working'
        run:
          python main.py --USERNAME ${{secrets.USERNAME}} --PASSWORD ${{secrets.PASSWORD}} --SPACE ${{secrets.SPACE}} --DAY ${{secrets.DAY}} --TIME ${{secrets.TIME}} --BOOKTIME ${{secrets.BOOKTIME}}
          

